language: python
matrix:
  include:
  - os: linux
    sudo: required
    python: 3.6
  - os: linux
    sudo: required
    python: 3.7
  - os: linux
    sudo: required
    python: 3.8


install:
  pip install -r requirements.txt
  pip install -r requirements-test.txt
script: pytest --cov=fbc_curation
after_success: pip install codecov; codecov
cache:
  directories:
  - "$HOME/.cache/pip"
