# -----------------------------------------------------------------------------
# DOCKER COMPOSE DEVELOPMENT
# -----------------------------------------------------------------------------
#
# build containers
#   docker-compose -f docker-compose-develop.yml build --no-cache
#   docker-compose -f docker-compose-develop.yml build
# serve containers
#   docker-compose -f docker-compose-develop.yml up --detach
#   docker-compose -f docker-compose-develop.yml up
# -----------------------------------------------------------------------------

version: '3'

volumes:
  vue_dist:
    driver: local
  node_modules:
    driver: local

services:

  backend:
    restart: always
    build: .
    volumes:
      - .:/code
    expose:
      - "80"
    ports:
      - "1556:80"
    command: ["/start.sh"]

  frontend:
    restart: always
    build:
      context: ./frog-site
      dockerfile: Dockerfile-develop
    ports:
      - "8085:4567"
    volumes:
      - ./frog-site:/app
      - node_modules:/app/node_modules/
      - vue_dist:/usr/share/nginx/html
